apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference3
  labels:
    app: online-inference3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-inference3
  template:
    metadata:
      name: online-inference3
      labels:
        app: online-inference3
    spec:
      containers:
        - image: akoshelev/online-inference:v6
          name: online-inference
          ports:
            - containerPort: 8000




