apiVersion: v1
kind: Pod
metadata:
  name: online-inference2
  labels:
    app: online-inference2
spec:
  containers:
    - image: akoshelev/online-inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 40
        periodSeconds: 5
