input_data_path: "data/heart.csv"
output_model_path: "models/logistic_regression.pkl"
output_data_preprocessor_path: "models/data_preprocessor.pkl"
logger_config: "configs/logger_config.yml"
model_type: "Logistic Regression"
split_params:
  validation_size: 0.25
  random_state: 23
feature_params:
  categorical_features: ['sex', 'cp', 'restecg', 'exang', 'slope', 'ca', 'thal']
  numerical_features: ['chol', 'thalach', 'oldpeak', 'trestbps', 'fbs', 'age']
  target: 'target'
classifier_params:
  C: 1.0
  penalty: "l2"
  fit_intercept: True
  random_state: 23
