input_data_path: "data/train.csv"
split_params:
  validation_size: 0.25
  random_state: 23
feature_params:
  categorical_features: ['sex', 'cp', 'restecg', 'exang', 'slope', 'ca', 'thal']
  numerical_features: ['chol', 'thalach', 'oldpeak', 'trestbps', 'fbs', 'age']
  target: 'target'
classifier_params:
  C: 1.0
  penalty: "l2"
  fit_intercept: True
  random_state: 23
