input_data_path: "data/heart.csv"
output_model_path: "models/random_forest.pkl"
output_data_preprocessor_path: "models/data_preprocessor.pkl"
logger_config: "configs/logger_config.yml"
model_type: "Random Forest Classifier"
split_params:
  validation_size: 0.1
  random_state: 23
feature_params:
  categorical_features: ['sex', 'cp', 'restecg', 'exang', 'slope', 'ca']
  numerical_features: ['chol', 'thalach', 'oldpeak', 'trestbps', 'fbs', 'age']
  target: 'target'
classifier_params:
  n_estimators: 100
  max_depth: 30
  random_state: 23
